import { createSlice } from '@reduxjs/toolkit';

// Define the LoaderState interface to represent the state structure
interface LoaderState {
  isLoading: boolean;
}

// Set the initial state for the loader slice
const initialState: LoaderState = {
  isLoading: false,
};

// Create the loader slice using createSlice from Redux Toolkit
const loaderSlice = createSlice({
  name: 'loader',
  initialState,
  reducers: {
    /**
     * Set the loader state to true.
     * @param state - The current state of the loader slice.
     */
    showLoader(state) {
      state.isLoading = true;
    },
    /**
     * Set the loader state to false.
     * @param state - The current state of the loader slice.
     */
    hideLoader(state) {
      state.isLoading = false;
    },
  },
});

// Export the actions generated by createSlice
export const { showLoader, hideLoader } = loaderSlice.actions;

// Export the reducer to be used in the store
export default loaderSlice.reducer;